export const services = [
  {
    id: 1,
    slug: "civil-engineering",
    title: "Civil Engineering",
    shortDescription: "Structures and site works built for safety, durability, and long-term value.",
    description: "Orisyn Limited provides practical civil engineering and construction solutions for buildings, infrastructure, and site-development projects. Every project is planned around structural reliability, efficient execution, safety, and lasting performance.",
    image: "/services/civil-engineering.png",
    imageAlt: "Construction team coordinating work on site",
    position: "object-center",
    items: ["Building Construction", "Structural Engineering", "Roads & Site Infrastructure", "Site Development", "Construction Planning", "Project Execution Support"],
    whyChooseUs: ["Experienced Engineering Team", "Safety-Focused Site Practices", "Quality-Controlled Delivery", "Durable Construction Solutions", "Reliable Project Coordination"],
  },
  {
    id: 2,
    slug: "electrical-electronic-engineering",
    title: "Electrical & Electronic Engineering",
    shortDescription: "Reliable power, control, and electronic systems for modern operations.",
    description: "We design, coordinate, supply, install, and support electrical and electronic systems for buildings, industrial facilities, and infrastructure. Our focus is safe installation, reliable performance, energy efficiency, and uninterrupted operation.",
    image: "/services/electrical-electronic-engineering.png",
    imageAlt: "Engineer inspecting an industrial electrical system",
    position: "object-center",
    items: ["Electrical Power Systems", "Distribution & Control Systems", "Panels & Protection Equipment", "Low-Voltage Systems", "Equipment Installation", "Inspection & Maintenance Support"],
    whyChooseUs: ["Qualified Technical Team", "Safe Installation Standards", "Energy-Efficient Solutions", "Dependable System Performance", "Responsive Maintenance Support"],
  },
  {
    id: 3,
    slug: "mechanical-engineering",
    title: "Mechanical Engineering",
    shortDescription: "Efficient machinery, HVAC, piping, and building-service solutions.",
    description: "Our mechanical engineering services support dependable building and industrial operations. We develop coordinated solutions that improve performance, maintainability, energy efficiency, and operational safety.",
    image: "/services/mechanical-engineering.png",
    imageAlt: "Engineer inspecting mechanical plant equipment",
    position: "object-center",
    items: ["HVAC Systems", "Machinery & Equipment Support", "Piping Systems", "Building Services", "Installation Coordination", "Maintenance Planning"],
    whyChooseUs: ["Practical Engineering Solutions", "Coordinated System Design", "Energy-Efficient Planning", "Operational Safety Focus", "Long-Term Maintenance Support"],
  },
  {
    id: 4,
    slug: "project-engineering",
    title: "Project Engineering",
    shortDescription: "Coordinated planning and delivery support from concept to completion.",
    description: "Orisyn Limited brings technical disciplines, stakeholders, schedules, and resources together through structured project engineering. We support informed decision-making and consistent delivery throughout the complete project lifecycle.",
    image: "/services/project-engineering.png",
    imageAlt: "Engineering team reviewing plans and a project model",
    position: "object-center",
    items: ["Project Planning", "Technical Coordination", "Design Review", "Schedule & Resource Coordination", "Procurement Support", "Delivery & Completion Support"],
    whyChooseUs: ["Multidisciplinary Expertise", "Structured Project Planning", "Clear Stakeholder Coordination", "Proactive Schedule Management", "End-to-End Delivery Support"],
  },
  {
    id: 5,
    slug: "import-export-supply",
    title: "Import, Export & Supply",
    shortDescription: "Dependable sourcing and supply support for every project requirement.",
    description: "We help clients source engineering materials, equipment, and project essentials from suitable local and international markets. Our approach emphasizes product quality, technical suitability, regulatory compliance, reliable coordination, and timely delivery.",
    image: "/services/import-export-supply.png",
    imageAlt: "Industrial equipment prepared for global shipping",
    position: "object-center",
    items: ["Global Product Sourcing", "Local Procurement", "International Procurement", "Import & Export Coordination", "Engineering Materials Supply", "Equipment Supply", "Logistics & Delivery Support"],
    whyChooseUs: ["Reliable Supplier Network", "Technical Product Evaluation", "Regulatory Compliance", "Efficient Logistics Coordination", "Dependable On-Time Delivery"],
  },
  {
    id: 6,
    slug: "investment",
    title: "Investment",
    shortDescription: "Strategic investment solutions that support sustainable growth and long-term value.",
    description: "Orisyn Limited identifies and supports responsible investment opportunities across engineering, infrastructure, construction, real estate, technology, and strategic business partnerships. We focus on transparent planning, practical risk management, sustainable growth, and lasting value for every stakeholder.",
    image: "/services/investment.png",
    imageAlt: "Professionals evaluating an infrastructure investment model",
    position: "object-center",
    items: ["Business Investment", "Project Financing", "Strategic Partnerships", "Infrastructure Investment", "Real Estate Investment", "Technology Investment", "Joint Venture Opportunities"],
    whyChooseUs: ["Strategic Investment Planning", "Transparent Business Practices", "Sustainable Growth Focus", "Practical Risk Management", "Long-Term Value Creation"],
  },
] as const;

export type Service = (typeof services)[number];

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
